In [1]:
import numpy as np

In [3]:
a = np.arange(1, 10)
a.shape = (3, -1)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#a = np.arange(1, 11).reshape((1, -1))
#a = np.apply_along_axis(lambda x: -1 if x % 2 == 1 else x, 0, a)
a = np.arange(1, 11)
a = np.where(a % 2 == 0, a, -1)
a

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [5]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
a = x > y
b = x == y
a = np.where(a)
b = np.where(b)
print(a, b)

(array([1, 2, 4, 5, 6, 7, 8, 9]),) (array([0]),)


In [6]:
a = np.arange(100).reshape(5,-1)
a[:, :4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

In [14]:
rng = np.random.default_rng()
rng.integers(30, 41, 10)

array([36, 33, 35, 38, 35, 35, 34, 37, 33, 34])

In [8]:
a = np.array(((1, 2, 3), (4, 5, 6), (7, 8, 10)))
b = np.array(((7, 8, 10) ,(4, 5, 6), (1, 2, 3)))
a, b

(array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]]),
 array([[ 7,  8, 10],
        [ 4,  5,  6],
        [ 1,  2,  3]]))

In [9]:
c = a + b
e = a - b
c, e

(array([[ 8, 10, 13],
        [ 8, 10, 12],
        [ 8, 10, 13]]),
 array([[-6, -6, -7],
        [ 0,  0,  0],
        [ 6,  6,  7]]))

In [10]:
a.sum(), np.apply_along_axis(np.sum, 0, b), np.apply_along_axis(np.sum, 1, c)

(46, array([12, 15, 19]), array([31, 30, 31]))

In [11]:
d = a * b
d

array([[ 7, 16, 30],
       [16, 25, 36],
       [ 7, 16, 30]])

In [12]:
#e = np.apply_along_axis(np.sort, 0, c.flatten()).reshape(c.shape)
e = np.sort(c.flatten()).reshape(c.shape)
e

array([[ 8,  8,  8],
       [10, 10, 10],
       [12, 13, 13]])

In [13]:
e.T

array([[ 8, 10, 12],
       [ 8, 10, 13],
       [ 8, 10, 13]])